# Generated by Django 3.1.5 on 2021-01-29 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210128_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='read_cnt',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
