# Generated by Django 3.1.5 on 2021-01-29 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210129_1134'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='count',
            new_name='read_cnt',
        ),
    ]
